packages:
  - "app"
  - "docs"
  - "packages/bindings"

dedupePeers: true
ignoreWorkspaceRootCheck: true
trustPolicy: no-downgrade

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - "@tb-dev/*"
  - "@tsukilabs/*"

allowBuilds:
  esbuild: false
  vue-demi: false
