packages:
  - "app"
  - "docs"
  - "crates/nil-continent/pkg"

ignoreWorkspaceRootCheck: true
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@tauri-apps/*"
  - "@tauri-store/*"
  - "@tb-dev/*"
  - "@tsukilabs/*"
  - "reka-ui"
  - "typescript"
  - "vite"
  - "vue"
