[package]
name = "nil-ffi"
publish = false

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
either.workspace = true
nil-client.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
