// dprint-ignore-file

//! Copyright (C) Call of Nil contributors
//! SPDX-License-Identifier: AGPL-3.0-only

import * as ffi from "node:ffi";

export const definitions = {
nil_ffi_free_str: { arguments: [ffi.types.POINTER], return: ffi.types.VOID },
nil_ffi_poll: { arguments: [ffi.types.POINTER], return: ffi.types.INT_32 },
nil_ffi_shutdown: { arguments: [], return: ffi.types.VOID },
nil_ffi_version: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_is_host: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_start_server: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_start_server_with_savedata: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_stop_server: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_client_version: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_is_local: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_is_ready: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_is_remote: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_server_addr: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_set_user_agent: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_stop_client: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_update_client: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_user_agent: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_world: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_runtime_global_queue_depth: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_runtime_num_alive_tasks: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_runtime_num_workers: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_add_academy_recruit_order: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_add_prefecture_build_order: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_add_stable_recruit_order: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_add_workshop_recruit_order: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_authorize: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_buy_resources: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cancel_academy_recruit_order: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cancel_maneuver: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cancel_prefecture_build_order: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cancel_stable_recruit_order: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cancel_workshop_recruit_order: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_fill_world: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_academy_recruit_queue: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_academy_recruit_queues: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_all_academy_recruit_queues: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_all_prefecture_build_queues: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_all_stable_recruit_queues: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_build_steps: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_cities: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_city: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_ethics: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_idle_armies_at: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_idle_personnel_at: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_infrastructure: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_maneuvers: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_maneuvers_of: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_player: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_players: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_prefecture_build_queue: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_prefecture_build_queues: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_resources: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_stable_recruit_queue: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_stable_recruit_queues: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_get_storage_capacity: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_set_bot_ethics: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_set_building_level: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_set_food: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_set_iron: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_set_market_fee: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_set_market_vault_resources: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_set_max_food: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_set_max_infrastructure: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_set_max_iron: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_set_max_resources: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_set_max_silo_resources: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_set_max_stone: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_set_max_warehouse_resources: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_set_max_wood: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_set_resources: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_set_stability: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_set_stone: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_set_wood: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_skip_round: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_spawn_bot: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_spawn_city: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_cheat_spawn_personnel: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_create_remote_world: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_create_user: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_delete_remote_world: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_forward_report: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_academy_recruit_catalog: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_armies: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_army: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_army_owner: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_bot_coords: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_chat_history: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_cities: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_city: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_city_score: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_continent_size: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_idle_armies_at: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_idle_armies_coords: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_maneuver: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_market: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_market_fee: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_player: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_player_coords: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_player_ids: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_player_maintenance: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_player_military: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_player_status: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_player_storage_capacity: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_player_worlds: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_precursor_coords: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_prefecture_build_catalog: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_public_bot: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_public_bots: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_public_cities: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_public_city: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_public_field: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_public_fields: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_public_player: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_public_players: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_public_precursor: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_public_precursors: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_rank: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_ranking: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_remote_world: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_remote_world_limit: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_get_remote_world_limit_per_user: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_get_remote_worlds: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_get_round: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_server_kind: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_get_stable_recruit_catalog: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_workshop_recruit_catalog: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_world_bots: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_world_config: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_world_personnel: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_world_players: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_world_precursors: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_world_rulers: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_get_world_stats: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_player_exists: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_push_chat_message: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_rename_city: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_request_maneuver: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_save_local_world: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_search_city: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_search_public_city: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_sell_resources: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_send_resources: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_server_version: { arguments: [ffi.types.UINT_32], return: ffi.types.VOID },
nil_set_player_ready: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_set_player_status: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_simulate_battle: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_spawn_player: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_start_round: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_toggle_building: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_user_exists: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
nil_validate_token: { arguments: [ffi.types.UINT_32, ffi.types.POINTER], return: ffi.types.VOID },
} as const;
