// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcademyRecruitQueue } from "./AcademyRecruitQueue";
import type { BuildingLevel } from "./BuildingLevel";

export type Academy = {
  level: BuildingLevel;
  enabled: boolean;
  recruitQueue: AcademyRecruitQueue;
};
