// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StableRecruitOrderRequest } from "./StableRecruitOrderRequest";
import type { WorldId } from "./WorldId";

export type AddStableRecruitOrderRequest = {
  world: WorldId;
  request: StableRecruitOrderRequest;
};
