// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { app_AcademySettings } from "./app_AcademySettings";
import type { app_AppearanceSettings } from "./app_AppearanceSettings";
import type { app_AuthSettings } from "./app_AuthSettings";
import type { app_GeneralSettings } from "./app_GeneralSettings";
import type { app_PrefectureSettings } from "./app_PrefectureSettings";
import type { app_StableSettings } from "./app_StableSettings";
import type { app_WorkshopSettings } from "./app_WorkshopSettings";

export type app_Settings = {
  academy: app_AcademySettings;
  appearance: app_AppearanceSettings;
  auth: app_AuthSettings;
  general: app_GeneralSettings;
  prefecture: app_PrefectureSettings;
  stable: app_StableSettings;
  workshop: app_WorkshopSettings;
};
