// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resources } from "./Resources";
import type { WorldId } from "./WorldId";

export type BuyResourcesRequest = { world: WorldId; resources: Resources };
