// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheatGetAllPrefectureBuildQueuesResponseItem } from "./CheatGetAllPrefectureBuildQueuesResponseItem";

export type CheatGetAllPrefectureBuildQueuesResponse = Array<
  CheatGetAllPrefectureBuildQueuesResponseItem
>;
