// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildStep } from "./BuildStep";

export type CheatGetBuildStepsResponse = Array<BuildStep>;
