// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ethics } from "./Ethics";

export type CheatGetEthicsResponse = Ethics | null;
