// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { City } from "./City";
import type { Score } from "./Score";

export type CheatGetCityResponse = { city: City; score: Score | null };
