// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coord } from "./Coord";
import type { Ruler } from "./Ruler";
import type { WorldId } from "./WorldId";

export type CheatSpawnCityRequest = {
  world: WorldId;
  ruler: Ruler | null;
  coord: Coord;
};
