// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Influence } from "./Influence";

export type CheatGetInfluenceResponse = Influence;
