// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheatGetAcademyRecruitQueuesResponseItem } from "./CheatGetAcademyRecruitQueuesResponseItem";

export type CheatGetAcademyRecruitQueuesResponse = Array<
  CheatGetAcademyRecruitQueuesResponseItem
>;
