// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Influence } from "./Influence";
import type { Ruler } from "./Ruler";
import type { WorldId } from "./WorldId";

export type CheatSetInfluenceRequest = {
  world: WorldId;
  ruler?: Ruler | null;
  influence: Influence;
};
