// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Password } from "./Password";
import type { PlayerId } from "./PlayerId";
import type { ServerAddr } from "./ServerAddr";
import type { Token } from "./Token";
import type { WorldId } from "./WorldId";

export type ClientOptions = {
  server: ServerAddr;
  worldId?: WorldId | null;
  worldPassword?: Password | null;
  playerId?: PlayerId | null;
  playerPassword?: Password | null;
  authorizationToken?: Token | null;
};
