// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Password } from "./Password";
import type { PlayerId } from "./PlayerId";

export type CreateUserRequest = { player: PlayerId; password: Password };
