// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";
import type { Coord } from "./Coord";
import type { PlayerId } from "./PlayerId";
import type { ReportKind } from "./ReportKind";
import type { Round } from "./Round";
import type { WorldId } from "./WorldId";

export type Event =
  | { "kind": "chat-message"; world: WorldId; message: ChatMessage }
  | { "kind": "city"; world: WorldId; coord: Coord }
  | { "kind": "drop"; world: WorldId }
  | { "kind": "military"; world: WorldId; player: PlayerId }
  | { "kind": "player"; world: WorldId; player: PlayerId }
  | { "kind": "public-city"; world: WorldId; coord: Coord }
  | { "kind": "report"; world: WorldId; report: ReportKind }
  | { "kind": "round"; world: WorldId; round: Round };
