// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";
import type { Coord } from "./Coord";
import type { EventId } from "./EventId";
import type { PlayerId } from "./PlayerId";
import type { ReportKind } from "./ReportKind";
import type { Round } from "./Round";
import type { WorldId } from "./WorldId";

export type Event =
  | {
    "kind": "chat-message";
    id: EventId;
    world: WorldId;
    message: ChatMessage;
  }
  | { "kind": "city"; id: EventId; world: WorldId; coord: Coord }
  | { "kind": "drop"; id: EventId; world: WorldId }
  | { "kind": "market"; id: EventId; world: WorldId }
  | { "kind": "military"; id: EventId; world: WorldId; player: PlayerId }
  | { "kind": "player"; id: EventId; world: WorldId; player: PlayerId }
  | { "kind": "public-city"; id: EventId; world: WorldId; coord: Coord }
  | { "kind": "report"; id: EventId; world: WorldId; report: ReportKind }
  | { "kind": "round"; id: EventId; world: WorldId; round: Round };
