// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ffi_QueueEntryKind } from "./ffi_QueueEntryKind";

export type ffi_QueueEntry = { kind: ffi_QueueEntryKind; json_str: string };
