// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export enum ffi_Status {
  "OK" = 0,
  "ERR_NULL_POINTER" = 1,
  "ERR_NOTHING_TO_POLL" = 2,
  "ERR_SERIALIZATION" = 3,
  "ERR_UNKNOWN" = 2147483647,
}
