// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Password } from "./Password";
import type { PlayerId } from "./PlayerId";
import type { ServerAddr } from "./ServerAddr";
import type { Token } from "./Token";
import type { WorldId } from "./WorldId";

export type ffi_UpdateClient = {
  server: ServerAddr;
  world_id?: WorldId | null;
  world_password?: Password | null;
  player_id?: PlayerId | null;
  player_password?: Password | null;
  authorization_token?: Token | null;
};
