// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ffi_RequestId } from "./ffi_RequestId";
import type { ffi_Status } from "./ffi_Status";
import type { JsonValue } from "./serde_json/JsonValue";

export type ffi_Response =
  & { id: ffi_RequestId }
  & ({ "kind": "ok"; data: JsonValue } | {
    "kind": "err";
    status: ffi_Status;
    error: string;
  });
