// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerId } from "./PlayerId";
import type { ReportKind } from "./ReportKind";
import type { WorldId } from "./WorldId";

export type ForwardReportRequest = {
  world: WorldId;
  recipient: PlayerId;
  report: ReportKind;
};
