// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArmyId } from "./ArmyId";
import type { WorldId } from "./WorldId";

export type GetArmyRequest = { world: WorldId; id: ArmyId };
