// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Army } from "./Army";
import type { Coord } from "./Coord";

export type GetArmiesResponse = Array<[Coord, Army]>;
