// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GetCityResponse } from "./GetCityResponse";

export type GetCitiesResponse = Array<GetCityResponse>;
