// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Gold is a special resource used to trade in the market.
 */
export type Gold = number;
