// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Food } from "./Food";

/**
 * Maintenance tax of an entity.
 *
 * Its value is equivalent to a percentage of the [base cost].
 *
 * [base cost]: crate::resources::cost::Cost
 */
export type Maintenance = Food;
