// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarketFee } from "./MarketFee";
import type { MarketVault } from "./MarketVault";

export type Market = { vault: MarketVault; fee: MarketFee };
