// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gold } from "./Gold";

export type MarketPrice = { food: Gold; iron: Gold; stone: Gold; wood: Gold };
