// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Amount of resources generated by a mine in a single round.
 */
export type MineProduction = number;
