// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingId } from "./BuildingId";
import type { BuildingLevel } from "./BuildingLevel";
import type { PrefectureBuildOrderId } from "./PrefectureBuildOrderId";
import type { PrefectureBuildOrderKind } from "./PrefectureBuildOrderKind";
import type { PrefectureBuildOrderState } from "./PrefectureBuildOrderState";
import type { Resources } from "./Resources";
import type { Workforce } from "./Workforce";

export type PrefectureBuildOrder = {
  id: PrefectureBuildOrderId;
  kind: PrefectureBuildOrderKind;
  building: BuildingId;
  level: BuildingLevel;
  resources: Resources;
  workforce: Workforce;
  state: PrefectureBuildOrderState;
};
