// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BotId } from "./BotId";
import type { PublicCapital } from "./PublicCapital";

export type PublicBot = { id: BotId; capital: PublicCapital };
