// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerId } from "./PlayerId";
import type { PlayerStatus } from "./PlayerStatus";
import type { PublicCapital } from "./PublicCapital";

export type PublicPlayer = {
  id: PlayerId;
  status: PlayerStatus;
  capital: PublicCapital;
};
