// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManeuverRequest } from "./ManeuverRequest";
import type { WorldId } from "./WorldId";

export type RequestManeuverRequest = {
  world: WorldId;
  request: ManeuverRequest;
};
