// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoundId } from "./RoundId";
import type { RoundState } from "./RoundState";

export type Round = {
  id: RoundId;
  state: RoundState;
  startedAt: string | null;
};
