// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingLevel } from "./BuildingLevel";
import type { Luck } from "./Luck";
import type { Squad } from "./Squad";
import type { WorldId } from "./WorldId";

export type SimulateBattleRequest = {
  world: WorldId;
  attacker: Array<Squad>;
  defender: Array<Squad>;
  luck: Luck;
  wall: BuildingLevel;
};
