// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Password } from "./Password";
import type { PlayerOptions } from "./PlayerOptions";
import type { WorldId } from "./WorldId";

export type SpawnPlayerRequest = {
  world: WorldId;
  worldPassword?: Password | null;
  options: PlayerOptions;
};
