// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents how many fields a unit can travel in one round.
 */
export type Speed = number;
