// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InfluenceResourceCost } from "./InfluenceResourceCost";
import type { InfrastructureStats } from "./InfrastructureStats";
import type { MarketPriceTable } from "./MarketPriceTable";

export type WorldStats = {
  infrastructure: InfrastructureStats;
  marketPriceTable: MarketPriceTable;
  influenceResourceCost: InfluenceResourceCost;
};
