[build]
rustflags = []

[unstable]
# See: https://github.com/rust-lang/cargo/issues/17009
min-publish-age = true

[registry]
global-min-publish-age = "3 days"

[env]
TS_RS_EXPORT_DIR = { value = "packages/bindings/src", relative = true }
