// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `user_data` table.
    ///
    /// (Automatically generated by Diesel.)
    user_data (id) {
        /// The `id` column of the `user_data` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `user` column of the `user_data` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        user -> Text,
        /// The `password` column of the `user_data` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        password -> Text,
    }
}

diesel::table! {
    /// Representation of the `world_data` table.
    ///
    /// (Automatically generated by Diesel.)
    world_data (id) {
        /// The `id` column of the `world_data` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `data` column of the `world_data` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        data -> Binary,
    }
}

diesel::allow_tables_to_appear_in_same_query!(user_data, world_data,);
