name: Release

on:
  push:
    branches: [release]

jobs:
  publish:
    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version: 26
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2026-07-20

      - name: Install dependencies
        run: pnpm ci

      - name: Crates.io auth
        uses: rust-lang/crates-io-auth-action@v1.0.5
        id: auth

      - name: Publish crates
        run: cargo -Zscript scripts/publish-crates.rs
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

      - name: Publish packages
        run: |
          pnpm run -F @tsukilabs/nil-bindings build
          cargo -Zscript scripts/publish-packages.rs

  release-client:
    needs: publish
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        include:
          - platform: ubuntu-24.04
            args: ""
          - platform: windows-latest
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version: 26
          cache: pnpm

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2026-07-20

      - name: Install dependencies (Ubuntu)
        if: matrix.platform == 'ubuntu-24.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install dependencies
        run: |
          pnpm ci
          pnpm run -F @tsukilabs/nil-bindings build
          pnpm run -F @tsukilabs/nil-i18n build

      - name: Run tests
        run: cargo -Zscript scripts/test.rs
        env:
          RUST_BACKTRACE: 1

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__
          releaseName: "Call of Nil v__VERSION__"
          releaseBody: ""
          releaseDraft: false
          prerelease: false
          uploadUpdaterJson: true
          updaterJsonPreferNsis: true
          generateReleaseNotes: false
          args: ${{ matrix.args }}

      - name: Build FFI library
        run: cargo -Zscript scripts/build-ffi.rs --publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_BACKTRACE: 1

  release-server:
    needs: release-client
    permissions:
      contents: write

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2026-07-20

      - name: Install dependencies (Ubuntu)
        run: sudo apt-get update

      - name: Release
        run: cargo -Zscript scripts/build-server.rs --publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_BACKTRACE: 1
          TSUKILABS_TOKEN: ${{ secrets.TSUKILABS_TOKEN }}
