// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcademyRecruitCatalogRecipe } from "./AcademyRecruitCatalogRecipe";
import type { InfrastructureRequirements } from "./InfrastructureRequirements";

export type AcademyRecruitCatalogEntry = {
  "kind": "available";
  recipe: AcademyRecruitCatalogRecipe;
} | { "kind": "unmet"; requirements: InfrastructureRequirements };
