// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcademyRecruitOrder } from "./AcademyRecruitOrder";

export type AcademyRecruitQueue = { orders: Array<AcademyRecruitOrder>, };
