// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcademyUnitId } from "./AcademyUnitId";
import type { Coord } from "./Coord";

export type AcademyRecruitOrderRequest = { coord: Coord, unit: AcademyUnitId, chunks: number, };
