// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcademyRecruitOrderId } from "./AcademyRecruitOrderId";
import type { AcademyRecruitOrderState } from "./AcademyRecruitOrderState";
import type { Resources } from "./Resources";
import type { Squad } from "./Squad";
import type { Workforce } from "./Workforce";

export type AcademyRecruitOrder = {
  id: AcademyRecruitOrderId;
  squad: Squad;
  resources: Resources;
  workforce: Workforce;
  state: AcademyRecruitOrderState;
};
