// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InfrastructureRequirements } from './InfrastructureRequirements';
import type { Maintenance } from './Maintenance';
import type { Resources } from './Resources';
import type { Workforce } from './Workforce';

export type AcademyRecruitCatalogRecipe = {
  resources: Resources;
  maintenance: Maintenance;
  workforce: Workforce;
  requirements: InfrastructureRequirements;
};
