// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcademyRecruitOrderRequest } from "./AcademyRecruitOrderRequest";
import type { WorldId } from "./WorldId";

export type AddAcademyRecruitOrderRequest = { world: WorldId, request: AcademyRecruitOrderRequest, };
