// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrefectureBuildOrderRequest } from "./PrefectureBuildOrderRequest";
import type { WorldId } from "./WorldId";

export type AddPrefectureBuildOrderRequest = {
  world: WorldId;
  request: PrefectureBuildOrderRequest;
};
