// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkshopRecruitOrderRequest } from './WorkshopRecruitOrderRequest';
import type { WorldId } from './WorldId';

export type AddWorkshopRecruitOrderRequest = {
  world: WorldId;
  request: WorkshopRecruitOrderRequest;
};
