// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManeuverId } from "./ManeuverId";

export type ArmyState = { "kind": "idle" } | { "kind": "maneuvering", maneuver: ManeuverId, };
