// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Squad } from './Squad';

export type ArmyPersonnel = {
  archer: Squad;
  axeman: Squad;
  heavyCavalry: Squad;
  lightCavalry: Squad;
  pikeman: Squad;
  ram: Squad;
  swordsman: Squad;
};
