// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArmyId } from "./ArmyId";
import type { ArmyPersonnel } from "./ArmyPersonnel";
import type { ArmyState } from "./ArmyState";
import type { Ruler } from "./Ruler";

export type Army = {
  id: ArmyId;
  personnel: ArmyPersonnel;
  owner: Ruler;
  state: ArmyState;
};
