// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArmyPersonnel } from './ArmyPersonnel';
import type { BattleWinner } from './BattleWinner';
import type { BuildingLevel } from './BuildingLevel';
import type { BuildingLevelDiff } from './BuildingLevelDiff';
import type { Luck } from './Luck';

export type BattleResult = {
  attackerPersonnel: ArmyPersonnel;
  attackerSurvivingPersonnel: ArmyPersonnel;
  defenderPersonnel: ArmyPersonnel;
  defenderSurvivingPersonnel: ArmyPersonnel;
  wallLevel: BuildingLevel;
  downgradedWallLevel: BuildingLevelDiff;
  winner: BattleWinner;
  luck: Luck;
};
