// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BattleResult } from "./BattleResult";
import type { Coord } from "./Coord";
import type { ReportId } from "./ReportId";
import type { Resources } from "./Resources";
import type { RoundId } from "./RoundId";
import type { Ruler } from "./Ruler";

export type BattleReport = { id: ReportId, attacker: Ruler, defender: Ruler, origin: Coord, destination: Coord, result: BattleResult, hauledResources: Resources, round: RoundId, time: string, };
