// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Proportion of bots that will have an advanced start with higher level infrastructure.
 */
export type BotAdvancedStartRatio = number;
