// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingId } from "./BuildingId";
import type { BuildingLevel } from "./BuildingLevel";

export type BuildStep = { id: BuildingId, level: BuildingLevel, };
