// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingLevel } from './BuildingLevel';
import type { Cost } from './Cost';
import type { Maintenance } from './Maintenance';
import type { Resources } from './Resources';
import type { Score } from './Score';
import type { Workforce } from './Workforce';

/**
 * Information about a building at a given level.
 */
export type BuildingStats = {
  level: BuildingLevel;
  cost: Cost;
  resources: Resources;
  maintenance: Maintenance;
  workforce: Workforce;
  score: Score;
};
