// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingId } from "./BuildingId";
import type { BuildingLevel } from "./BuildingLevel";
import type { BuildingStats } from "./BuildingStats";

export type BuildingStatsTable = {
  id: BuildingId;
  minLevel: BuildingLevel;
  maxLevel: BuildingLevel;
  table: { [key in BuildingLevel]: BuildingStats };
};
