// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcademyRecruitOrderId } from "./AcademyRecruitOrderId";
import type { Coord } from "./Coord";
import type { WorldId } from "./WorldId";

export type CancelAcademyRecruitOrderRequest = { world: WorldId, coord: Coord, id: AcademyRecruitOrderId, };
