// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coord } from './Coord';
import type { WorkshopRecruitOrderId } from './WorkshopRecruitOrderId';
import type { WorldId } from './WorldId';

export type CancelWorkshopRecruitOrderRequest = {
  world: WorldId;
  coord: Coord;
  id: WorkshopRecruitOrderId;
};
