// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessageAuthor } from "./ChatMessageAuthor";
import type { ChatMessageContent } from "./ChatMessageContent";
import type { ChatMessageId } from "./ChatMessageId";
import type { ChatMessageKind } from "./ChatMessageKind";

export type ChatMessage = {
  content: ChatMessageContent;
  id: ChatMessageId;
  kind: ChatMessageKind;
  author: ChatMessageAuthor;
  time: string;
};
