// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerId } from "./PlayerId";

export type ChatMessageAuthor = { "kind": "system" } | { "kind": "player", id: PlayerId, };
