// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ruler } from "./Ruler";
import type { WorldId } from "./WorldId";

export type CheatSetMaxResourcesRequest = { world: WorldId, ruler?: Ruler | null, };
