// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coord } from './Coord';
import type { WorldId } from './WorldId';

export type CheatGetPrefectureBuildQueuesRequest = {
  world: WorldId;
  coords: Array<Coord>;
  filterEmpty: boolean;
};
