// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Infrastructure } from './Infrastructure';
import type { WorldId } from './WorldId';

export type CheatSpawnBotRequest = {
  world: WorldId;
  name: string;
  infrastructure?: Infrastructure | null;
};
