// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BotId } from "./BotId";
import type { Ethics } from "./Ethics";
import type { WorldId } from "./WorldId";

export type CheatSetBotEthicsRequest = { world: WorldId, id: BotId, ethics?: Ethics | null, };
