// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArmyPersonnel } from "./ArmyPersonnel";
import type { Coord } from "./Coord";
import type { Ruler } from "./Ruler";
import type { WorldId } from "./WorldId";

export type CheatSpawnPersonnelRequest = { world: WorldId, coord: Coord, personnel: ArmyPersonnel, ruler?: Ruler | null, };
