// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ruler } from "./Ruler";
import type { Wood } from "./Wood";
import type { WorldId } from "./WorldId";

export type CheatSetWoodRequest = { world: WorldId, ruler?: Ruler | null, wood: Wood, };
