// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Food } from './Food';
import type { Ruler } from './Ruler';
import type { WorldId } from './WorldId';

export type CheatSetFoodRequest = {
  world: WorldId;
  ruler?: Ruler | null;
  food: Food;
};
