// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Iron } from "./Iron";
import type { Ruler } from "./Ruler";
import type { WorldId } from "./WorldId";

export type CheatSetIronRequest = { world: WorldId, ruler?: Ruler | null, iron: Iron, };
