// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coord } from './Coord';
import type { Stability } from './Stability';
import type { WorldId } from './WorldId';

export type CheatSetStabilityRequest = {
  world: WorldId;
  coord: Coord;
  stability: Stability;
};
