// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcademyRecruitQueue } from './AcademyRecruitQueue';
import type { Coord } from './Coord';

export type CheatGetAcademyRecruitQueuesResponse = Array<
  [Coord, AcademyRecruitQueue]
>;
