// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ruler } from "./Ruler";
import type { Stone } from "./Stone";
import type { WorldId } from "./WorldId";

export type CheatSetStoneRequest = { world: WorldId, ruler?: Ruler | null, stone: Stone, };
