// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingId } from "./BuildingId";
import type { BuildingLevel } from "./BuildingLevel";
import type { Coord } from "./Coord";
import type { WorldId } from "./WorldId";

export type CheatSetBuildingLevelRequest = { world: WorldId, coord: Coord, id: BuildingId, level: BuildingLevel, };
