// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CityName } from './CityName';
import type { Coord } from './Coord';
import type { Infrastructure } from './Infrastructure';
import type { Ruler } from './Ruler';
import type { Stability } from './Stability';

export type City = {
  coord: Coord;
  name: CityName;
  owner: Ruler;
  infrastructure: Infrastructure;
  stability: Stability;
};
