// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CityName } from "./CityName";
import type { Coord } from "./Coord";

export type CitySearch = { coord?: Array<Coord>; name?: Array<CityName> };
