// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Base cost of an entity, such as buildings or units.
 */
export type Cost = number;
