// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Password } from './Password';
import type { RoundDuration } from './RoundDuration';
import type { WorldOptions } from './WorldOptions';

export type CreateRemoteWorldRequest = {
  options: WorldOptions;
  description?: string | null;
  password?: Password | null;
  roundDuration?: RoundDuration | null;
};
