// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EthicPowerAxis } from "./EthicPowerAxis";
import type { EthicTruthAxis } from "./EthicTruthAxis";

export type Ethics = { power: EthicPowerAxis; truth: EthicTruthAxis };
