// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";
import type { Coord } from "./Coord";
import type { PlayerId } from "./PlayerId";
import type { ReportId } from "./ReportId";
import type { Round } from "./Round";
import type { WorldId } from "./WorldId";

export type Event = { "kind": "chat-updated", world: WorldId, message: ChatMessage, } | { "kind": "city-updated", world: WorldId, coord: Coord, } | { "kind": "drop", world: WorldId, } | { "kind": "military-updated", world: WorldId, player: PlayerId, } | { "kind": "player-updated", world: WorldId, player: PlayerId, } | { "kind": "public-city-updated", world: WorldId, coord: Coord, } | { "kind": "report", world: WorldId, report: ReportId, } | { "kind": "round-updated", world: WorldId, round: Round, };
