// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportId } from './ReportId';

export type GetPlayerReportsResponse = Array<ReportId>;
