// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GetPublicCityResponse } from "./GetPublicCityResponse";

export type GetPublicCitiesResponse = Array<GetPublicCityResponse>;
