// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerId } from "./PlayerId";
import type { WorldId } from "./WorldId";

export type GetPublicPlayerRequest = { world: WorldId; id: PlayerId };
