// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Maintenance } from './Maintenance';

export type GetPlayerMaintenanceResponse = Maintenance;
