// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrecursorId } from "./PrecursorId";
import type { WorldId } from "./WorldId";

export type GetPrecursorCoordsRequest = { world: WorldId, id: PrecursorId, };
