// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coord } from "./Coord";
import type { WorldId } from "./WorldId";

export type GetPublicCitiesRequest = { world: WorldId, coords: Array<Coord>, score: boolean, all: boolean, };
