// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Influence is a special resource which represents the political power of a ruler
 * and is used to determine how many cities they can simultaneously control.
 *
 * The amount of influence needed to control a number `n` of cities is given by
 * the formula `n * (n + 1) / 2`, meaning it increases as a triangular number.
 */
export type Influence = number;
