// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingLevel } from "./BuildingLevel";

export type InfrastructureRequirements = { academy: BuildingLevel, farm: BuildingLevel, ironMine: BuildingLevel, prefecture: BuildingLevel, quarry: BuildingLevel, sawmill: BuildingLevel, silo: BuildingLevel, stable: BuildingLevel, wall: BuildingLevel, warehouse: BuildingLevel, workshop: BuildingLevel, };
