// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Academy } from './Academy';
import type { Farm } from './Farm';
import type { IronMine } from './IronMine';
import type { Prefecture } from './Prefecture';
import type { Quarry } from './Quarry';
import type { Sawmill } from './Sawmill';
import type { Silo } from './Silo';
import type { Stable } from './Stable';
import type { Wall } from './Wall';
import type { Warehouse } from './Warehouse';
import type { Workshop } from './Workshop';

export type Infrastructure = {
  academy: Academy;
  farm: Farm;
  ironMine: IronMine;
  prefecture: Prefecture;
  quarry: Quarry;
  sawmill: Sawmill;
  silo: Silo;
  stable: Stable;
  wall: Wall;
  warehouse: Warehouse;
  workshop: Workshop;
};
