// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingId } from './BuildingId';
import type { BuildingStatsTable } from './BuildingStatsTable';
import type { MineId } from './MineId';
import type { MineStatsTable } from './MineStatsTable';
import type { StorageId } from './StorageId';
import type { StorageStatsTable } from './StorageStatsTable';
import type { WallStatsTable } from './WallStatsTable';

export type InfrastructureStats = {
  building: { [key in BuildingId]?: BuildingStatsTable; };
  mine: { [key in MineId]?: MineStatsTable; };
  storage: { [key in StorageId]?: StorageStatsTable; };
  wall: WallStatsTable;
};
