// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resources } from './Resources';
import type { Ruler } from './Ruler';

export type ManeuverHaul = { ruler: Ruler; resources: Resources; };
