// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArmyPersonnel } from './ArmyPersonnel';
import type { Coord } from './Coord';
import type { ManeuverKind } from './ManeuverKind';

export type ManeuverRequest = {
  kind: ManeuverKind;
  origin: Coord;
  destination: Coord;
  personnel: ArmyPersonnel;
};
