// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArmyId } from "./ArmyId";
import type { Coord } from "./Coord";
import type { ManeuverDirection } from "./ManeuverDirection";
import type { ManeuverHaul } from "./ManeuverHaul";
import type { ManeuverId } from "./ManeuverId";
import type { ManeuverKind } from "./ManeuverKind";
import type { ManeuverState } from "./ManeuverState";
import type { Speed } from "./Speed";

export type Maneuver = { id: ManeuverId, origin: Coord, destination: Coord, army: ArmyId, kind: ManeuverKind, direction: ManeuverDirection, state: ManeuverState, speed: Speed, hauledResources: ManeuverHaul | null, };
