// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Army } from "./Army";
import type { ContinentIndex } from "./ContinentIndex";
import type { ContinentSize } from "./ContinentSize";
import type { Maneuver } from "./Maneuver";
import type { ManeuverId } from "./ManeuverId";

export type Military = {
  continent: { [key in ContinentIndex]: Array<Army> };
  continentSize: ContinentSize;
  maneuvers: { [key in ManeuverId]: Maneuver };
};
