// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingLevel } from "./BuildingLevel";
import type { MineId } from "./MineId";
import type { MineStats } from "./MineStats";

export type MineStatsTable = {
  id: MineId;
  table: { [key in BuildingLevel]: MineStats };
};
