// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Influence } from './Influence';
import type { PlayerId } from './PlayerId';
import type { PlayerStatus } from './PlayerStatus';
import type { Resources } from './Resources';

export type Player = {
  id: PlayerId;
  status: PlayerStatus;
  resources: Resources;
  influence: Influence;
};
