// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InfrastructureRequirements } from "./InfrastructureRequirements";
import type { PrefectureBuildCatalogRecipe } from "./PrefectureBuildCatalogRecipe";

export type PrefectureBuildCatalogEntry = { "kind": "available", recipe: PrefectureBuildCatalogRecipe, } | { "kind": "maxed" } | { "kind": "unmet", requirements: InfrastructureRequirements, };
