// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingLevel } from "./BuildingLevel";
import type { InfrastructureRequirements } from "./InfrastructureRequirements";
import type { Maintenance } from "./Maintenance";
import type { Resources } from "./Resources";
import type { Workforce } from "./Workforce";

export type PrefectureBuildCatalogRecipe = { level: BuildingLevel, resources: Resources, maintenance: Maintenance, workforce: Workforce, requirements: InfrastructureRequirements, };
