// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingId } from "./BuildingId";
import type { Coord } from "./Coord";
import type { PrefectureBuildOrderKind } from "./PrefectureBuildOrderKind";

export type PrefectureBuildOrderRequest = { coord: Coord, building: BuildingId, kind: PrefectureBuildOrderKind, };
