// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingLevel } from './BuildingLevel';
import type { PrefectureBuildQueue } from './PrefectureBuildQueue';

export type Prefecture = {
  level: BuildingLevel;
  enabled: boolean;
  buildQueue: PrefectureBuildQueue;
};
