// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrefectureBuildCatalogEntry } from './PrefectureBuildCatalogEntry';

export type PrefectureBuildCatalog = {
  academy: PrefectureBuildCatalogEntry;
  farm: PrefectureBuildCatalogEntry;
  ironMine: PrefectureBuildCatalogEntry;
  prefecture: PrefectureBuildCatalogEntry;
  quarry: PrefectureBuildCatalogEntry;
  sawmill: PrefectureBuildCatalogEntry;
  silo: PrefectureBuildCatalogEntry;
  stable: PrefectureBuildCatalogEntry;
  wall: PrefectureBuildCatalogEntry;
  warehouse: PrefectureBuildCatalogEntry;
  workshop: PrefectureBuildCatalogEntry;
};
