// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coord } from "./Coord";
import type { Ruler } from "./Ruler";

/**
 * Public data about a city, to which any player can have access.
 */
export type PublicCity = { coord: Coord; name: string; owner: Ruler };
