// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicCity } from './PublicCity';

/**
 * Public data about a field, to which any player can have access.
 */
export type PublicField = { kind: 'empty'; } | {
  kind: 'city';
  city: PublicCity;
};
