// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coord } from "./Coord";
import type { PrecursorId } from "./PrecursorId";

export type PublicPrecursor = { id: PrecursorId, origin: Coord, };
