// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingLevel } from './BuildingLevel';

export type Quarry = { level: BuildingLevel; enabled: boolean; };
