// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rank } from "./Rank";
import type { Ruler } from "./Ruler";
import type { Score } from "./Score";

export type RankingEntry = { rank: Rank, ruler: Ruler, score: Score, cities: number, };
