// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContinentSize } from "./ContinentSize";
import type { PlayerId } from "./PlayerId";
import type { RoundDuration } from "./RoundDuration";
import type { RoundId } from "./RoundId";
import type { WorldConfig } from "./WorldConfig";

export type RemoteWorld = {
  config: WorldConfig;
  description: string | null;
  createdBy: PlayerId;
  createdAt: string;
  updatedAt: string;
  hasPassword: boolean;
  currentRound: RoundId;
  roundDuration: RoundDuration | null;
  activePlayers: number;
  totalPlayers: number;
  continentSize: ContinentSize;
};
