// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportId } from "./ReportId";
import type { WorldId } from "./WorldId";

export type RemoveReportRequest = { world: WorldId, id: ReportId, };
