// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BattleReport } from "./BattleReport";
import type { SupportReport } from "./SupportReport";

export type ReportKind = { "kind": "battle", report: BattleReport, } | { "kind": "support", report: SupportReport, };
