// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Food } from "./Food";
import type { Iron } from "./Iron";
import type { Stone } from "./Stone";
import type { Wood } from "./Wood";

export type Resources = { food: Food, iron: Iron, stone: Stone, wood: Wood, };
