// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerId } from "./PlayerId";

export type RoundState = { "kind": "idle" } | { "kind": "waiting", pending: Array<PlayerId>, ready: Array<PlayerId>, } | { "kind": "done" };
