// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BotId } from './BotId';
import type { PlayerId } from './PlayerId';
import type { PrecursorId } from './PrecursorId';

export type Ruler = { kind: 'bot'; id: BotId; } | {
  kind: 'player';
  id: PlayerId;
} | { kind: 'precursor'; id: PrecursorId; };
