// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CitySearch } from "./CitySearch";
import type { WorldId } from "./WorldId";

export type SearchCityRequest = { world: WorldId, search: CitySearch, };
