// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerStatus } from "./PlayerStatus";
import type { WorldId } from "./WorldId";

export type SetPlayerStatusRequest = { world: WorldId, status: PlayerStatus, };
