// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BattleResult } from './BattleResult';

export type SimulateBattleResponse = BattleResult;
