// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SquadSize } from "./SquadSize";
import type { UnitBox } from "./UnitBox";

/**
 * A group of units of the same type.
 */
export type Squad = { unit: UnitBox, size: SquadSize, };
