// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InfrastructureRequirements } from './InfrastructureRequirements';
import type { StableRecruitCatalogRecipe } from './StableRecruitCatalogRecipe';

export type StableRecruitCatalogEntry = {
  kind: 'available';
  recipe: StableRecruitCatalogRecipe;
} | { kind: 'unmet'; requirements: InfrastructureRequirements; };
