// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resources } from './Resources';
import type { Squad } from './Squad';
import type { StableRecruitOrderId } from './StableRecruitOrderId';
import type { StableRecruitOrderState } from './StableRecruitOrderState';
import type { Workforce } from './Workforce';

export type StableRecruitOrder = {
  id: StableRecruitOrderId;
  squad: Squad;
  resources: Resources;
  workforce: Workforce;
  state: StableRecruitOrderState;
};
