// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingLevel } from './BuildingLevel';
import type { StorageId } from './StorageId';
import type { StorageStats } from './StorageStats';

export type StorageStatsTable = {
  id: StorageId;
  table: { [key in BuildingLevel]: StorageStats; };
};
