// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArmyPersonnel } from "./ArmyPersonnel";
import type { Coord } from "./Coord";
import type { ReportId } from "./ReportId";
import type { RoundId } from "./RoundId";
import type { Ruler } from "./Ruler";

export type SupportReport = { id: ReportId, sender: Ruler, receiver: Ruler, origin: Coord, destination: Coord, personnel: ArmyPersonnel, round: RoundId, time: string, };
