// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingLevel } from './BuildingLevel';
import type { WallDefense } from './WallDefense';
import type { WallDefenseBonus } from './WallDefenseBonus';

export type WallStats = {
  level: BuildingLevel;
  defense: WallDefense;
  defensePercent: WallDefenseBonus;
};
