// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingLevel } from './BuildingLevel';
import type { WallStats } from './WallStats';

export type WallStatsTable = { [key in BuildingLevel]: WallStats; };
