// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingLevel } from './BuildingLevel';
import type { WorkshopRecruitQueue } from './WorkshopRecruitQueue';

export type Workshop = {
  level: BuildingLevel;
  enabled: boolean;
  recruitQueue: WorkshopRecruitQueue;
};
