// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coord } from './Coord';
import type { WorkshopUnitId } from './WorkshopUnitId';

export type WorkshopRecruitOrderRequest = {
  coord: Coord;
  unit: WorkshopUnitId;
  chunks: number;
};
