// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InfrastructureRequirements } from "./InfrastructureRequirements";
import type { WorkshopRecruitCatalogRecipe } from "./WorkshopRecruitCatalogRecipe";

export type WorkshopRecruitCatalogEntry = { "kind": "available", recipe: WorkshopRecruitCatalogRecipe, } | { "kind": "unmet", requirements: InfrastructureRequirements, };
