// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Workforce } from "./Workforce";

export type WorkshopRecruitOrderState = { "kind": "pending", workforce: Workforce, } | { "kind": "done" };
