// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resources } from './Resources';
import type { Squad } from './Squad';
import type { Workforce } from './Workforce';
import type { WorkshopRecruitOrderId } from './WorkshopRecruitOrderId';
import type { WorkshopRecruitOrderState } from './WorkshopRecruitOrderState';

export type WorkshopRecruitOrder = {
  id: WorkshopRecruitOrderId;
  squad: Squad;
  resources: Resources;
  workforce: Workforce;
  state: WorkshopRecruitOrderState;
};
