// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workforce is a special resource used to construct buildings and recruit troops.
 * The amount generated per round will always be equal to the level of the relevant
 * building multiplied by the world speed.
 *
 * Unlike other resources, workforce should never accumulate for the next round.
 * Anything that is not used should be discarded.
 */
export type Workforce = number;
