// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BotAdvancedStartRatio } from './BotAdvancedStartRatio';
import type { BotDensity } from './BotDensity';
import type { ContinentSize } from './ContinentSize';
import type { Locale } from './Locale';
import type { WorldName } from './WorldName';
import type { WorldSpeed } from './WorldSpeed';
import type { WorldUnitSpeed } from './WorldUnitSpeed';

export type WorldOptions = {
  name: WorldName;
  size: ContinentSize;
  locale: Locale;
  allowCheats: boolean;
  speed: WorldSpeed;
  unitSpeed: WorldUnitSpeed;
  botDensity: BotDensity;
  botAdvancedStartRatio: BotAdvancedStartRatio;
};
