// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InfrastructureStats } from './InfrastructureStats';

export type WorldStats = { infrastructure: InfrastructureStats; };
